event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# FosUserBundle routes
_user_import:
    resource: "@UserBundle/Resources/config/routing.yml"
    